development:
  mailchimp_api_key: cd7b07d737fd4be94613a67b46507190-us16
  app_host: http://staging.upixel.ca
  email: mattresshospitalityinc@gmail.com
  password: johnstarkman
  domain: gmail.com
  secret_key_base: 84ef9e3a3032d77467dc6d95e988f2f128e6acc7513661e3e6b67a875d99bebabf19571d02d2ddb9face07dc45cb9aba821b4e93c2619deb2fee55a23818292c
  database:
    host: 127.0.0.1
    name: henao_master_orig_development
    username: root
    password: 123456
  ga_auth:
    :service_account_email_address: 911375046727-9n50de61u7flmue7s76qelsthlhqhnnl@developer.gserviceaccount.com
    :file_key_name: gauth_key.p12
    :account_id: 87102409

test:
  mailchimp_api_key: cd7b07d737fd4be94613a67b46507190-us16
  app_host: http://staging.upixel.ca
  email: mattresshospitalityinc@gmail.com
  password: johnstarkman
  domain: gmail.com
  secret_key_base: 84ef9e3a3032d77467dc6d95e988f2f128e6acc7513661e3e6b67a875d99bebabf19571d02d2ddb9face07dc45cb9aba821b4e93c2619deb2fee55a23818292c
  database:
    host: 127.0.0.1
    name: henao_master_orig_tester
    username: root
    password: 123456
  ga_auth:
    :service_account_email_address: 571486246044-51ef6884ea7dd21b0f9c72092cf59c8403393554@developer.gserviceaccount.com
    :file_key_name: gauth_key.p12
    :account_id: 87102409
  mailchimp:
    :api_key: 92fcf4de42fa9d7f7bd922da9f808292-us13
    :list: 655d17e904
  google_sign:
    :client_id: 469077599597-l1k1uig7ptd7jftronvielnrm77ipu5c.apps.googleusercontent.com
    :secret_key: 59i5jXKSw0cFxmsYjg_vhCQP
  shippo:
    :secret_key: cc8af24b6efe4cef09715e52dea1ff4d21f729e6
  stripe:
    :secret_key: sk_test_BKgX0Huvb4pC2PnlAC6R0OI5
    :publishable_key: pk_test_sy3tBVZu0AjeXIcbqMu8jn2I
  paypal:
    :business: gbrlmrllo-facilitator@gmail.com
    :host: https://www.sandbox.paypal.com/cgi-bin/webscr?
  mercado_pago:
    :client_id: 4548281425975469
    :client_secret: KYBBSyvkkK5kH3gNFh1iSyP1fVmDvCYR9

production:

  mailchimp_api_key: cd7b07d737fd4be94613a67b46507190-us16
  app_host: <%= ENV['APP_HOST'] %>
  email: <%= ENV['EMAIL_USERNAME'] %>
  password: <%= ENV['EMAIL_PASSWORD'] %>
  domain: gmail.com
  address: smtp.gmail.com
  port: 465
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  database:
    host: 127.0.0.1
    name: henao_master_orig_development
    username: root
    password: 123456
  ga_auth:
    :service_account_email_address: <%= ENV['SERVICE_ACCOUNT_EMAIL_ADDRESS'] %>
    :file_key_name: gauth_key.p12
    :account_id: <%= ENV['ACCOUNT_ID'] %>
  mailchimp:
    :api_key: <%= ENV['MAILCHIMP_API_KEY'] %>
    :list: <%= ENV['MAILCHIMP_LIST'] %>
  google_sign:
    :client_id: <%= ENV['GOOGLE_PLUS_ID'] %>
    :secret_key: <%= ENV['GOOGLE_PLUS_SECRET'] %>
  shippo:
    :secret_key: <%= ENV['SHIPPO_SECRET_KEY'] %>
  stripe:
    :secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
    :publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
  paypal:
    :business: <%= ENV['PAYPAL_BUSINESS'] || nil %>
    :host: https://www.sandbox.paypal.com/cgi-bin/webscr?
  mercado_pago:
    :client_id: <%= ENV['MERCADOPAGO_CLIENT_ID'] || nil %>
    :client_secret: <%= ENV['MERCADOPAGO_CLIENT_SECRET'] || nil %>
